import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className="fixed top-0 left-0 h-16 w-16">Contacts</div>
          <div className='fixed top-0 right-0 h-16 w-16'>info@backstagetalks.com</div>
      </main>

    </div>
  )
}
